// File generated by FlutterFire CLI.
// ignore_for_file: require_trailing_commas, unnecessary_import

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBplURphCslF22Ox9RckOL9JHxD9ZiLk0w",
    authDomain: "katotasksapp.firebaseapp.com",
    projectId: "katotasksapp",
    storageBucket: "katotasksapp.firebasestorage.app",
    messagingSenderId: "280313492350",
    appId: "1:280313492350:web:7c091ae60228a1ed62b92f",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBplURphCslF22Ox9RckOL9JHxD9ZiLk0w",
    appId: "1:280313492350:web:7c091ae60228a1ed62b92f",
    messagingSenderId: "280313492350",
    projectId: "katotasksapp",
    storageBucket: "katotasksapp.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyYourKeyForiOS",
    appId: "1:YourAppId:ios:yourCode",
    messagingSenderId: "280313492350",
    projectId: "katotasksapp",
    storageBucket: "katotasksapp.firebasestorage.app",
    iosClientId: "YOUR_iOS_CLIENT_ID",
    iosBundleId: "com.example.kato_tasks_app",
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = android;
}




